### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by TheLudd** [cullophid/date-fp#2]
Hello.
I very much like the idea of this project but I was unable to run this in node due to some build problems. Mainly the `build` folder was not included in the package. I also found some other room for improvement. I could fix all of these but would like to check first:
- The built files are included in source control, remove?
- Add the files and directories that should be included in the npm package in "files" in package.json
- Add source maps
- Export the module to umd format which will make it usable in node, require-js or globally in the browser.

I can easily fix all these unless there is any objection

**Comment by cullophid** [comment]
Hi @TheLudd 
You are very right on all points :)
You are very welcome to submit a PR, otherwise we will get on it very soon :)

**Comment by cullophid** [comment]
Can I close this ? @TheLudd

**Comment by TheLudd** [comment]
Consider it done

**Comment by cullophid** [comment]
Thanks for the help :)
