### ISSUE TITLE
Invalid Input To D.format

### ISSUE THREAD

**Issue by svozza** [cullophid/date-fp#32]
Say a user does something silly like this:

``` js
D.format('B', new Date())
// => 'B'
```

Obviously this output is as nonsensical as the input but how - or even, should - we guard against this happening? What is the appropriate response here when we can't throw an error. Should we just return the string `Invalid Date`?

**Comment by cullophid** [comment]
Thats not an error. It makes no obvious sense, but we are definately returning the expected value.
