### ISSUE TITLE
Support week numbers in formatting and parsing

### ISSUE THREAD

**Issue by TheLudd** [cullophid/date-fp#35]
Could this be added? Has it been discussed? I could perhaps take a look at it

**Comment by cullophid** [comment]
its quite easy to add to formatting.
How would it work in parsing ?

**Comment by TheLudd** [comment]
Don't really know if pasing is neccesary. Just thought it would be symmmetrical. But formatting is where I need it.

**Comment by cullophid** [comment]
parse( "week WW, YYYY", "week 35, 2016") // ?

**Comment by TheLudd** [comment]
That would be one possible use and it should give the start of that week I suppose.
But perhaps it is for the best to just do formatting and hold off parsing until there are actual requirements.

**Comment by cullophid** [comment]
its easy enough to add to formatting
You are very welcome to do a PR if you like.

https://github.com/cullophid/date-fp/blob/master/src/format.js

all you need to do is add a handler in `tokenFunctions`

maybe use http://momentjs.com/docs/#/displaying/format/ for reference

If you prefer I can do it over the weekend

**Comment by TheLudd** [comment]
Think I can do it today

**Comment by cullophid** [comment]
@TheLudd  https://github.com/cullophid/date-fp/pull/36

**Comment by TheLudd** [comment]
Thanks, sorry I just forgot this...
