### ISSUE TITLE
Support for get('day')

### ISSUE THREAD

**Issue by wuct** [cullophid/date-fp#38]
Hi, thanks for this awesome lib. I use it in my current project happily.

I find out there is no `get('Day')` currently which supports to get a weekday from a Date instance, like what [`Date.prototype.getDay`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) does.

I am not sure it is a good idea to add this feature to this lib. If it looks good to you, I would like to create a PR for it.

**Comment by svozza** [comment]
I don't think this is an unreasonable request.

**Comment by wuct** [comment]
@svozza just open a PR. Please review it. Thanks in advance :)

**Comment by cullophid** [comment]
PR: https://github.com/cullophid/date-fp/pull/39
