### ISSUE TITLE
get timezoneOffset test fails

### ISSUE THREAD

**Issue by TheLudd** [cullophid/date-fp#42]
On my local machine, the test for get timezoneOffset fails

```
  1) get should return timezoneOffset:

      AssertionError: -60 == -120
      + expected - actual

      --60
      +-120
```

I suspect that summer time is the problem here. If I change the input date from January to June the test will pass which means that getTimeZone returns the offset in my current timeZone at the specific time of the date. 

We can change the test so that the input date always have the same offset as the date being tested. Either way, this is new information to me.

**Comment by svozza** [comment]
Fixed by #43
