### ISSUE TITLE
Publish modularized files

### ISSUE THREAD

**Issue by wuct** [cullophid/date-fp#44]
`date-fp` is published as a single build file, which forces consumers to required all functions in their bundles.

Maybe we can also release separated compiled-to-ES5 files, and consumers can required the only functions they need.

I would like to implement this if it looks good to you :)

**Comment by cullophid** [comment]
Sounds good.
We already have function specific es6 modules, so this should simply be a matter of compiling the files.

**Comment by cullophid** [comment]
https://github.com/cullophid/date-fp/pull/45
