### ISSUE TITLE
https://evilcorp.limited/date-fp - Your connection is not secure

### ISSUE THREAD

**Issue by kedashoe** [cullophid/date-fp#50]
Looks like something is up with the documentation website

**Comment by cullophid** [comment]
yeah thats quite annoying. I tried a company called kloud  (I think) that provided free ssl for github sites... they went bankrupt, and my site went down...

**Comment by cullophid** [comment]
the docs are available on the http version

**Comment by davidchambers** [comment]
You could use Cloudflare, @cullophid.
