### ISSUE TITLE
Question: compose get('day') and sub('days')

### ISSUE THREAD

**Issue by simonhaenisch** [cullophid/date-fp#61]
I have the following `compose` implementation:

```js
compose = (...fns) => data => fns.reduceRight((value, func) => func(value), data);
```

I am quite new to functional programming and want to compose `get('day')` and `sub('days')`:

```js
const { get, sub, format } = require('date-fp');

const previousSunday = compose(sub('days'), get('day'));

const date = new Date();
```

Now if I call `previousSunday(date)`, it returns a (curried?) `get('day', n)` function (`n` being the value returned from `sub()`), which I have to call again with a date argument, e. g. `previousSunday(date)(date)`.

How can I compose those functions in a way that I only have to pass the date once? I eventually want to compose that with `format()` as well, i. e.:

```js
const previousSundayThisWeek = previousSunday(date);
const formatPreviousSunday = compose(format('YYYY-MM-DD'), previousSundayThisWeek);
const sunday = formatPreviousSunday(date);
```

I would rather want to compose all those functions so that I can only pass the date once, but I can't see how to compose them properly. Something like...

```js
const previousSunday = compose(format('YYYY-MM-DD'), sub('days'), get('day'))(date);
```

wouldn't work of course.

Any help or hints are greatly appreciated. Thanks!

**Comment by cullophid** [comment]
I don't think I would use point free style here..
```
const previousSunday = date => sub('days', get('day', date), date) ;
```

now you can do

```
const formatPreviousSunday = compose(format(''YYYY-MM-DD'),previousSunday)
```

**Comment by simonhaenisch** [comment]
Ok, thanks for your help! That makes sense... first creating a function that takes and returns a date, so it's easily composable. I practiced some more fp and start to understand the concepts better now. Thanks a lot for this package and the docs, really helped me to get into it!

**Comment by cullophid** [comment]
@simonhaenisch Happy hacking!
