### ISSUE TITLE
Strange warning

### ISSUE THREAD

**Issue by fingermark** [cullophid/date-fp#8]
Get this when I use date-fp in my project:

WARNING in ./~/date-fp/build/date-fp.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/date-fp/build/date-fp.js 1:479-486

**Comment by cullophid** [comment]
Yes, This is because we are building date-fp with browserify. We are currently looking into how to solve this. In webpack (wich I believe is throwing the error message) this should not cause problems.

**Comment by cullophid** [comment]
This was fixed in 1.2.6
